### ISSUE TITLE
run command failed

### ISSUE THREAD

**Issue by xxyz30** [SereinMC/Serein#161]
```
>> serein build
SyntaxError: Unexpected identifier
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:139:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:236:14)
    at async link (node:internal/modules/esm/module_job:67:21)
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: gulp build
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at Object.exec (file:///C:/Users/ts187/AppData/Roaming/npm/node_modules/@pureeval/serein/src/base/io.js:33:16)
    at Command.<anonymous> (file:///C:/Users/ts187/AppData/Roaming/npm/node_modules/@pureeval/serein/src/executer/cli.js:46:19)
    at Command.listener [as _actionHandler] (C:\Users\ts187\AppData\Roaming\npm\node_modules\@pureeval\serein\node_modules\.store\commander@11.1.0\node_modules\commander\lib\command.js:494:17)
    at C:\Users\ts187\AppData\Roaming\npm\node_modules\@pureeval\serein\node_modules\.store\commander@11.1.0\node_modules\commander\lib\command.js:1296:65
    at Command._chainOrCall (C:\Users\ts187\AppData\Roaming\npm\node_modules\@pureeval\serein\node_modules\.store\commander@11.1.0\node_modules\commander\lib\command.js:1193:12)
    at Command._parseCommand (C:\Users\ts187\AppData\Roaming\npm\node_modules\@pureeval\serein\node_modules\.store\commander@11.1.0\node_modules\commander\lib\command.js:1296:27)
    at C:\Users\ts187\AppData\Roaming\npm\node_modules\@pureeval\serein\node_modules\.store\commander@11.1.0\node_modules\commander\lib\command.js:1082:27
    at Command._chainOrCall (C:\Users\ts187\AppData\Roaming\npm\node_modules\@pureeval\serein\node_modules\.store\commander@11.1.0\node_modules\commander\lib\command.js:1193:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 11444,
  stdout: null,
  stderr: null
}
```

**Comment by xxyz30** [comment]
![图片](https://github.com/SereinMC/Serein/assets/81208875/c0ee21db-477a-44b1-9310-4075b4ad268d)
然后新建的模板，写代码会这个样子

**Comment by CAIMEOX** [comment]
> ![图片](https://private-user-images.githubusercontent.com/81208875/307496856-c0ee21db-477a-44b1-9310-4075b4ad268d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTIzMjEsIm5iZiI6MTcwODc1MjAyMSwicGF0aCI6Ii84MTIwODg3NS8zMDc0OTY4NTYtYzBlZTIxZGItNDc3YS00NGIxLTkzMTAtNDA3NWI0YWQyNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1MjAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MGIzODllYTIzMzhlZmZiMmQ1ZWIxOGFmOTE4YWU3ODllMThjNDgwMTFmZTg2MWMzMGY4N2Y0ZWQ5ODQyMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1C5VsBewWnuPYIaccD88WyeTJJE2yuOYSjzSWMrhDGE) 然后新建的模板，写代码会这个样子

Fix this by adding `"moduleResolution":"node"` to `compilerOptions` in `tsconfig.json`. The patch will be updated to main branch soon

**Comment by CAIMEOX** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/81208875/307496856-c0ee21db-477a-44b1-9310-4075b4ad268d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTIzMjEsIm5iZiI6MTcwODc1MjAyMSwicGF0aCI6Ii84MTIwODg3NS8zMDc0OTY4NTYtYzBlZTIxZGItNDc3YS00NGIxLTkzMTAtNDA3NWI0YWQyNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1MjAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MGIzODllYTIzMzhlZmZiMmQ1ZWIxOGFmOTE4YWU3ODllMThjNDgwMTFmZTg2MWMzMGY4N2Y0ZWQ5ODQyMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1C5VsBewWnuPYIaccD88WyeTJJE2yuOYSjzSWMrhDGE) 然后新建的模板，写代码会这个样子
> 
> Fix this by adding `"moduleResolution":"node"` to `compilerOptions` in `tsconfig.json`. The patch will be updated to main branch soon

fixed in #162

**Comment by Lampese** [comment]
刚才解决的是第二个问题，把Node版本更新到v18+再试试，可以用nvm，不一定要重装Node。

v16是相当老的版本了，写大部分东西都不提倡使用了。别看版本号高，Node加入新版本号标准之后有一段时间版本迭代的飞快，和v8 v11那个年代没法比。

**Comment by xxyz30** [comment]
> 刚才解决的是第二个问题，把Node版本更新到v18+再试试第一个问题解决没有，可以用nvm，不一定要重装Node。
> 
> v16是相当老的版本了，写大部分东西都不提倡使用了。别看版本号高，Node加入新版本号标准之后有一段时间版本迭代的飞快，和v8 v11那个年代没法比。

我更新了20可以解决这个问题
